[[JavaBase]]
class Demo{
%%Метод генерирует контролируемое исключение%%
	static void generator() throws IllegalAccessException{
		System.out.println("Выполняется метод");
%%Генерирование исключения%%
		throw new IllegalAccessException("Большая Ошибка");
	}
%%Главный метод%%
	public static void main(String[] args){
%%Контролируемый код%%
		try{
%%Вызов метода, генерирующего исключение%%
			generator();
%%Обработка ошибки%%
		}catch(IllegalAccessException e){
			System.out.println("Есть проблема:");
			System.out.println("<"+e+">");
		}
	}
}

Результат выполнения программы

Выполняется метод
Есть проблема:
<java.lang.IllegalAccessException: Большая Ошибка>